apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd

spec:
  destination:
    name: kind-vault-lab
    namespace: vault
  project: default
  sources:
  
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    helm:
      valueFiles: 
      - $values/argocd-vault-integration/applications/vault/values.yaml
    targetRevision: 0.28.1
  - repoURL: https://github.com/ageorgiev-bg/devopszen.git
    targetRevision: alex-testing
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true