apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: grafana
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    helm:
      valueFiles: 
      - $values/lab-log-monitoring/applications/grafana/values.yaml
    targetRevision: 8.0.2
  - repoURL: https://github.com/rafimojabi/devopszen.git 
    targetRevision: lab-log-generator
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true